### ISSUE TITLE
Travis CI build fails

### ISSUE THREAD

**Issue by Ritzlgrmft** [Ritzlgrmft/ionic-configuration-service#3]
https://travis-ci.org/Ritzlgrmft/ionic-configuration-service/builds/205330344:

```
$ npm test
> ionic-configuration-service@0.0.0-development test /home/travis/build/Ritzlgrmft/ionic-configuration-service
> npm run compile && npm run lint && npm run karma-once
> ionic-configuration-service@0.0.0-development compile /home/travis/build/Ritzlgrmft/ionic-configuration-service
> ngc
Error: Error at /home/travis/build/Ritzlgrmft/ionic-configuration-service/node_modules/@types/jasmine/index.d.ts:39:38: A parameter initializer is only allowed in a function or constructor implementation.
Error at /home/travis/build/Ritzlgrmft/ionic-configuration-service/node_modules/@types/jasmine/index.d.ts:39:46: Cannot find name 'keyof'.
Error at /home/travis/build/Ritzlgrmft/ionic-configuration-service/node_modules/@types/jasmine/index.d.ts:39:52: '=' expected.
    at check (/home/travis/build/Ritzlgrmft/ionic-configuration-service/node_modules/@angular/tsc-wrapped/src/tsc.js:31:15)
    at Tsc.typeCheck (/home/travis/build/Ritzlgrmft/ionic-configuration-service/node_modules/@angular/tsc-wrapped/src/tsc.js:86:9)
    at /home/travis/build/Ritzlgrmft/ionic-configuration-service/node_modules/@angular/tsc-wrapped/src/main.js:33:23
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
Compilation failed
```

**Comment by Ritzlgrmft** [comment]
dev dependency `@types/jasmine@^2.5.40` installed version `2.5.43`, which needs typescript 2.1. The solution is to fix `@types/jasmine to` to version `2.5.41`.
